INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Marko Petrović','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Akita: Na prodaju prelepi štenci akite, jedne od najodanijih rasa pasa. Ovi štenci su pravi mali krzneni čupavci i već su pokazali svoju nežnost prema ljudima. Akite su poznate po svom hrabrom i časnom karakteru, čineći ih idealnim izborom za porodice koje traže odanog člana porodice.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Prelep štenac akite traži novi dom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Ana Jovanović','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Nemački ovčar: Prodajem nemačkog ovčara, pasmine koja je poznata po svojoj izuzetnoj inteligenciji i vernosti. Ovaj pas je veoma odan i može postati izvanredan čuvar i pratilac za vašu porodicu. Nemački ovčar je spreman da vas zaštiti i voli bezuslovno.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Spreman za avanturu: Prodajem nemačkog ovčara',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Nikola Đorđević','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Džek rasel terijer: Mali džek rasel terijer štenci su živahni, veseli i puni ljubavi. Ovo su inteligentni psi koji su spremni da vas prate u svim avanturama. Ovi štenci će doneti mnogo radosti u vaš dom i postati pravi član porodice.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Mali džek rasel terijer traži vlasnika',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Ivana Simić','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Beagle: Beagle štenci su poznati po svojoj privrženosti i veselosti. Ovo su psi koji vole igru i druženje, čineći ih idealnim za porodice sa decom. Beagle je ljubazan pas i uvek je spreman za zabavu.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Razigrani beagle štenci čekaju nove porodice',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Darko Nikolić','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Labrador retriver: Labrador retriveri su omiljeni širom sveta zbog svoje odanosti i prijateljskog karaktera. Ovi psi su idealni za porodice i decu. Vole da se igraju, šetaju i budu deo porodičnih aktivnosti.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Elegantan labrador retriver za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Marija Popović','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Pomeranac: Pomeranci su poznati po svojoj lepoti i šarmu. Ovo su mali psi sa velikim srcem i neodoljivim izgledom. Pomeranac je idealan pratilac i ulepšaće svaki trenutak u vašem životu.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Pomeranac - najslađi kućni ljubimac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Luka Novak','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Golden retriver: Golden retriveri su poznati po svojoj nežnosti i spremnosti za igru. Ovi psi su izuzetno privrženi i vole da budu u društvu ljudi. Postanite ponosni vlasnik ovog predivnog psa koji će vas ulepšati svaki dan.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Golden retriver: Verni pratilac za celu porodicu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Jelena Milenković','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Rotvajler: Čistokrvni rotvajler štenci su snažni i odani čuvari. Ova pasmina je poznata po svojoj hrabrosti i vernosti. Rotvajleri su izuzetno inteligentni i brzo se prilagođavaju porodičnom životu.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Čistokrvni rotvajler štenci u potrazi za ljubavlju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Dušan Tomić','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Sibirski haski: Sibirski haski su prelepi psi poznati po svojoj gracioznosti i energiji. Ovi psi su idealni za aktivne vlasnike koji vole dugačke šetnje i avanture u prirodi. Has',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','affenpinscher','Sibirski haski: Pustolovina u vašem domu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Nataša Stojanović','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Francuski buldog: Francuski buldog je mali šampion sa velikim srcem. Ovi psi su veseli, odani i spremni da vas prate u svim avanturama. Francuski buldog je odličan izbor za sve uzraste i idealan za život u stanu ili kući.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','afghanHound','Francuski buldog - Mali šampion u potrazi za novim domom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Aleksandar Milić','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Cocker spanijel: Cocker spanijel štenci su veseli, druželjubivi i puni života. Ovi psi su poznati po svojoj nežnosti i spremnosti da pruže bezuslovnu ljubav. Postanite vlasnik ovih divnih kerova i uživajte u njihovoj veseloj prirodi.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','afghanHound','Cocker spanijel: Vesela štenad traži porodicu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Milica Milosavljević','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Doberman: Doberman je pas sa stilom. Snažan i odan, ovaj pas je savršen izbor za one koji traže zaštitnika i vernog pratioca. Dobermani su hrabri i inteligentni, čineći ih idealnim za porodice i pojedince koji cene odanost.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','afghanHound','Doberman: Zaštitnik i prijatelj u jednom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Stefan Vuković','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Labradudl: Labradudl je prelep i neodoljiv mešanac labradora i pudlice. Ovi psi su pametni, veseli i spremni za igru. Labradudli su idealni za porodice sa decom i ljude svih uzrasta.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','afghanHound','Labradudl: Pametan i neodoljiv pas za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Katarina Kostić','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Belgijski ovčar: Belgijski ovčar je radan i privržen pas, poznat po svojoj odanosti i hrabrosti. Ovi psi su odlični čuvari i veoma su posvećeni svojoj porodici. Postanite vlasnik ovog elegantnog i zaštitnički nastrojenog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Belgijski ovčar: Radan i verni pratilac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Uroš Ilić','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Pomorandžasti retriver: Pomorandžasti retriver štenci su spremni za igru i maženje. Ovi psi su vesele prirode i vole da provode vreme sa ljudima. Postanite vlasnik ovih maza i uživajte u njihovoj neodoljivoj šarmantnosti.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Pomorandžasti retriver štenci spremni za igru',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Dragana Pavlović','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mops: Mops je smešan, ljubazan i prepun ličnosti. Ovi psi su odlični pratilaci i uvek će vas nasmejati svojim nestašlucima. Mopsi su idealni za one koji vole blisku interakciju sa svojim ljubimcima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Mops: Simpatični pratioc za svaki dan',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Ivan Mitić','381621112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Pit bul terijer: Pit bul terijeri su snažni, hrabri i inteligentni psi. Ovi psi su izuzetno verni svojim vlasnicima i spremni da ih zaštite. Postanite vlasnik ovog izuzetno odanog i hrabrog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Pit bul terijer: Snalažljiv i snažan pas za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Teodora Janković','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Dalmatinac: Dalmatinci su prepoznatljivi po svojim tačkama i veseloj prirodi. Ovi psi su idealni za porodice i vole da provode vreme sa decom. Postanite vlasnik ovog čarobnog i energičnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Dalmatinac: Tačkasti čarobnjak u potrazi za porodicom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Mihajlo Arsić','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Šarplaninac: Šarplaninac je odan čuvar i prijatelj koji će sa ponosom čuvati vašu porodicu. Ovi psi su hrabri, samopouzdani i spremni da se brinu o svojim vlasnicima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Šarplaninac: Odlučan čuvar i prijatelj',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Anđela Đorđević','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Border kolie: Border kolie je inteligentan i energičan pas koji voli fizičke i mentalne izazove. Ovi psi su odani i spremni da učestvuju u svim aktivnostima. Postanite vlasnik ovog zaista pametnog psa i zajedno istražujte svet.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Nemirni border kolie čeka novu avanturu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Milan Ristić','381621122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Šar pej: Šar pej je nežan i odan pas koji će vam pružiti mnogo ljubavi i radosti. Ovi psi su poznati po svojim karakterističnim osmehom i privrženošću prema svojim vlasnicima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Šar pej: Nežan i odan pas za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Sanja Jovanov','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Šnaucer: Šnaucer je elegantan i samouveren pas. Ovi psi su odani svojim vlasnicima i spremni da ih prate u svim avanturama. Sa svojom lepom kosom i šarmantnim izgledom, šnaucer će privući pažnju svih u okolini.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Šnaucer: Elegantan i samouveren pratilac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Dejan Stanković','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Maltezer: Maltezeri su mali, beli psi koji su mekani kao pamučni oblaci. Ovi psi su prepuni nežnosti i odani svojim vlasnicima. Maltezeri su idealni kućni ljubimci za sve generacije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Maltezer: Mala bela kuglica sreće',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Jovana Simić','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Ruski hrt: Ruski hrtovi su poznati po svojoj brzini i gracioznosti. Ovi psi su elegantni i nežni, a istovremeno energični i vesele prirode. Postanite vlasnik ovog prelepog lovnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Ruski hrt: Brz i graciozan lovac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Aleksa Petrović','381621112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Bul terijer: Bul terijeri su snažni i hrabri psi koji se često opisuju kao veliki psi u malim telima. Ovi psi su prepuni energije i vole igru. Postanite vlasnik ovog hrabrog i živahnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Bul terijer: Snaga i hrabrost u malom pakovanju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Milena Popović','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Rajski papagaj: Ako tražite egzotičnog kućnog ljubimca, rajski papagaj je odličan izbor. Ovi šareni ptice su inteligentni i vole druženje sa svojim vlasnicima. Osim toga, imaju divne pernate boje koje će uneti šarenilo u vaš dom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Rajski papagaj: Egzotični kućni ljubimac za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Nenad Radovanović','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Irski seter: Irski seter je elegantan i energičan pas poznat po svojoj prelepim crvenim krznom. Ovi psi su ljubazni, veseli i spremni za igru. Postanite vlasnik ovog šarmantnog psa i uživajte u svakom trenutku.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Irski seter: Elegantan i energičan pas',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Sofija Lukić','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Ćorki: Mešavina šarmanata i veseljaka, ćorki je pas koji će vas nasmejati svojim šarmom. Ovi psi su živahni, pametni i spremni za druženje. Ćorki će postati sjajan član vaše porodice.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Ćorki: Mešavina šarmanata i veseljaka',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Viktorija Đorđević','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Bolonjezer: Bolonjezeri su mali psi koji su mekani kao pamučni oblak. Ovi psi su nežni i odani, i vole da budu u centru pažnje. Postanite vlasnik ovog čarobnog psa i osetite njegovu nežnost svakog dana.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Bolonjezer: Mekan kao pamučni oblak',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Aleksandar Janković','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Majmunski pinč: Majmunski pinč je pametan i šašav pas koji će vas nasmejati svojim nestašlucima. Ovi psi su odani svojim vlasnicima i vole da učestvuju u raznim zabavama. Majmunski pinč će dodati veselje u vaš život.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Majmunski pinč: Pametan i šašav',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Maša Perić','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Ratni terijer: Ratni terijeri su snalažljivi i privrženi ljubimci koji su spremni za akciju. Ovi psi su hrabri i odani svojim vlasnicima, čineći ih idealnim partnerima za avanture.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','airedaleTerrier','Ratni terijer: Snalažljiv i privržen ljubimac za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Stefan Stojanović','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Irski vodeni španijel: Irski vodeni španijeli su odani i spremni za igru. Ovi psi su poznati po svojoj inteligenciji i vole da budu u vodi. Ako volite vodene aktivnosti, ovaj pas će biti savršen izbor.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','akita','Irski vodeni španijel: Odan i spreman za igru',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Emilija Gajić','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Belgijski ovčar: Belgijski ovčar je aktivan pas poznat po svojoj posvećenosti. Ovi psi su svestrani i spremni da rade sve, od zaštite do sportskih aktivnosti. Postanite vlasnik ovog radnog psa i imaćete vernog pratilaca.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','akita','Belgijski ovčar: Aktivan i zaštitnički nastrojen',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Ognjen Jovanović','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Briar: Briar je ljubazan i elegantan pas koji je odličan izbor za porodice. Ovi psi su privrženi svojim vlasnicima i spremni za igru. Postanite vlasnik ovog čarobnog psa i uživajte u njegovom društvu.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Briar: Ljubazan i elegantan pas za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Tara Đorđević','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Retro stajeni bulterijer: Retro stajeni bulterijeri su mali, hrabri i simpatični psi. Ovi psi su odani svojim vlasnicima i vole da se igraju. Retro stajeni bulterijeri će uneti mnogo radosti u vaš dom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Retro stajeni bulterijer: Malen, hrabar i simpatičan',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Uroš Marinković','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Engleski seter: Engleski seteri su veseli i elegantni psi koji vole da provode vreme napolju. Ovi psi su odani svojim vlasnicima i spremni za igru. Postanite vlasnik ovog prelepog i energičnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Engleski seter: Veseo i elegantan pratilac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Mina Nikolić','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Tibetanski terijer: Tibetanski terijer je pahuljasti prijatelj za ceo život. Ovi psi su nežni, odani i vole da budu u društvu ljudi. Tibetanski terijeri će vam pružiti mnogo ljubavi i sreće.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Tibetanski terijer: Pahuljasti prijatelj za ceo život',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Stefan Milanović','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Australijski ovčar: Australijski ovčar je inteligentan pas koji je spreman za igru i aktivnosti. Ovi psi su odani svojim vlasnicima i vole da uče nove trikove. Postanite vlasnik ovog pametnog i živahnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Australijski ovčar: Inteligentan i živahno štene',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Ksenija Janković','381621112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Pekinezer: Pekinezeri su kraljevski pratilac za posebne trenutke. Ovi psi su elegantni, odani i vole da budu u centru pažnje. Pekinezeri će uneti dodatnu eleganciju u vaš dom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Pekinezer: Kraljevski pratilac za posebne trenutke',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Lazar Radosavljević','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Kavalirski kralj Čarls španijel: Kavalirski kralj Čarls španijeli su umiljati i odani psi koji vole druženje. Ovi psi su poznati po svojo',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Kavalirski kralj Čarls španijel: Umiljat i odan pas za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Elena Petrović','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Nova Škotska patuljasta retriver: Nova Škotska patuljasta retriver je mali veseljak sa prelepim narandžastim krznom. Ovi psi su puni radosti i privrženosti. Vole igru i šetnje, i idealni su za porodice koje traže veselog i odanog ljubimca.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Nova Škotska patuljasta retriver: Mali veseljak',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Aleksandar Milosavljević','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Saluki: Saluki je pas poznat po svojoj eleganciji i brzini. Ovi psi su nežni i odani svojim vlasnicima, spremni za brze trke i istraživanje prirode. Postanite vlasnik ovog čarobnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Saluki: Elegancija i brzina u jednom pakovanju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Tamara Tomić','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Basenji: Basenji je pas poznat po svojoj nezavisnosti i šarmu. Ovi psi su veseli i živahni, čineći ih odličnim izborom za aktivne vlasnike. Basenji će vas zabaviti svojim jedinstvenim karakterom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Basenji: Nezavisni i šarmantni kućni ljubimac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Aleksandar Simić','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Šnauzer minijatura: Šnauzer minijatura je očaravajući mali čuvar. Ovi psi su hrabri i inteligentni, spremni da čuvaju svoju porodicu. Istovremeno su odani i veseli, čineći ih savršenim kućnim ljubimcima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Šnauzer minijatura: Očaravajući mali čuvar',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Jovana Kostić','381621122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Nemački lovački terijer: Nemački lovački terijeri su snažni i odani pratioci. Ovi psi su hrabri i spremni za svaku avanturu. Vole fizičke aktivnosti i provođenje vremena sa svojim vlasnicima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Nemački lovački terijer: Snažan i odan pratioc',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Dušan Stojanović','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Doberman: Doberman je elegantan zaštitnik za svaku porodicu. Ovi psi su hrabri i odani svojim vlasnicima, spremni da ih zaštite. Dobermani su inteligentni i brzo uče, čineći ih savršenim čuvarima i prijateljima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Doberman: Elegantan zaštitnik za svaku porodicu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Mia Jovanović','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Airedale terijer: Airedale terijer je pametan i radoznao pas koji je spreman za svaku avanturu. Ovi psi su veseli i odani, spremni da pruže bezuslovnu ljubav. Postanite vlasnik ovog prelepog i energičnog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Airedale terijer: Pametan i radoznao pas za prodaju',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Nemanja Mitić','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Vajmaraner: Vajmaraner je energičan i privržen ljubimac koji će biti vaš verni pratilac. Ovi psi su pametni i vole fizičke aktivnosti. Vajmaraneri će uneti mnogo radosti u vaš život.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Vajmaraner: Energičan i privržen ljubimac',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Marija Radovanović','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Tibetski mastif: Tibetanski mastif je veliki čuvar i nežan prijatelj. Ovi psi su hrabri i spremni da štite svoju porodicu. Istovremeno su odani i privrženi, čineći ih idealnim čuvarima i pratiocima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Tibetski mastif: Veliki čuvar i nežan prijatelj',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','dogs','Jelena Stanković','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Dalmatinski retriver: Dalmatinski retriver je veselo štene za novi dom. Ovi psi su puni energije i ljubavi prema igri. Dalmatinski retriveri su poznati po svojim tačkama i karakterističnom izgledu. Postanite vlasnik ovog čarobnog i veselog psa.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','alapahaBlueBloodBulldog','Dalmatinski retriver: Veselo štene za novi dom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));





INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Luna','381601234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Prelepa škotska mačka traži novi dom. Ova elegantna dama ima mekano krzno i divan karakter. Verna i nežna, ona će biti savršeni dodatak vašoj porodici.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','abyssinian','Prelepa škotska mačka traži novi dom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Miloš','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mladi Maine Coon mačići dostupni za usvajanje. Ovi divni krzneni klinci su prepuni energije i vole igru. Postanite njihov heroj i pružite im ljubav.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','abyssinian','Mačići Maine Coon-a dostupni za usvajanje',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Tigris','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Egzotična persijska mačka spremna za novu porodicu. Njen luksuzni krzneni ogrtač čini je pravom kraljicom. Veoma odana i elegantna, ova mačka će osvojiti vaše srce.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','abyssinian','Egzotična persijska mačka spremna za novu porodicu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Mica','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Bengalski mačići - divlji izgled u vašem domu. Aktivni, inteligentni i spremni za avanture. Postanite ponosni vlasnik ovih divljih lepotica.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','abyssinian','Bengalski mačići - čiste divljine u vašem domu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Simba','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačke Sijamske rase za prave ljubitelje. Njihova jedinstvena lepota i odanost čine ih posebnim. Očekujte nežnost i privrženost ovih elegantnih ljubimaca.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aegean','Mačke Sijamske rase za pravog ljubitelja',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Lili','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mladi Britanski plavi mačići traže ljubav. Krzno poput pliša i divan karakter. Ovi mačići će vam pružiti nežnost i radost svakog dana.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aegean','Mladi Britanski plavi mačići traže ljubav',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Puf','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Savršenstvo u krznu: Ragdoll mačići dostupni. Mirni, ljubazni i spremni za maženje. Očekujte da vas obuzme ova neodoljiva mekoća.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Savršenstvo u krznu: Ragdoll mačići dostupni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Cezar','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Sphynx mačići - ljubav bez krzna. Njihova gola koža i radoznala priroda čine ih posebnim. Postanite vlasnik ovih unikatnih ljubimaca.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Sphynx mačići - ljubav bez krzna',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Bella','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Nevjerojatni mačići Scottish Fold traže dom. Njihove presavijene uši i simpatičan izgled osvajaju sve. Očekujte da vas ovi mačići očaraju svojom posebnošću.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Nevjerojatni mačići Scottish Fold traže dom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Šapko','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mladi mačići Burmese - dragoceni kao zlato. Vole igru i pažnju. Postanite vlasnik ovih zlatnih mačaka i upoznajte pravu vrednost ljubavi.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Mladi mačići Burmese - dragoceni kao zlato',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Maks','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Ljubazni mačići Oriental Shorthair spremni za usvajanje. Njihova energija i šarm čine ih posebnim. Očekujte da budete zadivljeni njihovim karakterom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Ljubazni mačići Oriental Shorthair spremni za usvajanje',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Marmelada','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Tajlandske mačke - divne i odane. Njihova elegancija i odanost čine ih savršenim ljubimcima. Postanite vlasnik ove tajlandske lepote.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Tajlandske mačke - divne i odane',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Tijana','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Divlji izgled i nežna priroda - Savannah mačići. Ovi mali divljaci spremni su za igru i istraživanje. Postanite deo njihove divlje avanture.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Divlji izgled i nežna priroda - Savannah mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Bubi','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Sreća u malom pakovanju: Exotic Shorthair mačići. Njihova neodoljiva širina lica i kratka krznena čarolija čine ih posebnim. Očekujte da vas osvoje.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Sreća u malom pakovanju: Exotic Shorthair mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Zara','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Pouzdani prijatelji: Russian Blue mačići traže dom. Njihova plava krzna i nežna priroda čine ih idealnim pratiocima. Postanite deo njihove elegantne priče.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Pouzdani prijatelji: Russian Blue mačići traže dom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Šumko','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačke Abyssinian - živahne i zabavne. Njihova energija i ljubav prema igri osiguravaju vam neprestano zadovoljstvo. Postanite vlasnik ove veselosti.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Mačke Abyssinian - živahne i zabavne',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Oskar','381621112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Najlepši Persijski mačići traže porodicu. Njihova lepota i nežnost osvajaju sva srca. Očekujte da vam pruže bezuslovnu ljubav.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanBobtail','Najlepši Persijski mačići traže porodicu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Lola','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Jedinstveni i elegantni: Balinese mačići. Njihova dugačka krzna i graciozan izgled čine ih posebnim. Postanite vlasnik ovih čarobnih lepotica.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanCurl','Jedinstveni i elegantni: Balinese mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Tobi','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Tonkinese mačići - lepotom i karakterom obdareni. Njihova energija i nežnost čine ih savršenim dodatkom porodici. Očekujte da budete očarani njihovim prisustvom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanShorthair','Tonkinese mačići - lepotom i karakterom obdareni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Maksim','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Čarobni mačići Munchkin spremni za igru. Njihove kratke noge i nestašluci čine ih jedinstvenim. Postanite vlasnik ove male čarolije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanShorthair','Čarobni mačići Munchkin spremni za igru',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Šnjuf','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Norveške šumske mačke - divlina u vašem domu. Njihova divlja priroda i lepota osiguravaju vam nezaboravno iskustvo. Postanite deo njihove priče.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanShorthair','Norveške šumske mačke - divljina u vašem domu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Lara','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačići Scottish Fold - slatki i jedinstveni. Njihove presavijene uši i nežna priroda čine ih posebnim. Očekujte da vam osvoje srce svojom posebnošću.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanShorthair','Mačići Scottish Fold - slatki i jedinstveni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Buca','381621122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Radoznale mačke Havana Brown spremne za igru. Njihova energija i živahnost osiguravaju vam puno smeha. Postanite vlasnik ove zabavne energije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Radoznale mačke Havana Brown spremne za igru',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Cica','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Egzotični Bengal mačići traže avanturiste. Njihov divlji izgled i hrabrost čine ih neodoljivim. Očekujte da vas odvedu na neverovatne avanture.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Egzotični Bengal mačići traže avanturiste',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Plavi','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačke Sphynx - jedinstvene i nežne. Njihova gola koža i ljubaznost čine ih posebnim. Postanite vlasnik ovih unikatnih ljubimaca.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Mačke Sphynx - jedinstvene i nežne',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Džimi','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mekani kao oblaci: Ragamuffin mačići dostupni. Njihova mekoća i nežnost osiguravaju vam puno maženja. Očekujte da budete obasuti ljubavlju.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Mekani kao oblaci: Ragamuffin mačići dostupni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Nala','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Sišuamaska elegancija: Siamese mačići. Njihova elegancija i karakter čine ih posebnim. Postanite deo njihove priče o ljubavi.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Sišuamaska elegancija: Siamese mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Pufi','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mladi Burmese mačići traže svoju porodicu. Njihova igra i veselje čine ih posebnim. Očekujte da vas osvoje svojom energijom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Mladi Burmese mačići traže svoju porodicu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Tigrica','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačići Bengal - divlji izgled u vašem domu. Njihova energija i šarm čine ih jedinstvenim. Postanite vlasnik ove divlje lepote.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Mačići Bengal - divlji izgled u vašem domu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Kiki','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Najslađi domaći tigrovi: Ocicat mačići. Njihova šarenila i odanost osiguravaju vam neprocenjivu vezu. Postanite vlasnik ove divlje elegancije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Najslađi domaći tigrovi: Ocicat mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Balerina','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Egzotične mačke Devon Rex - igračke uživo. Njihova kovrdžava krzna i veselost čine ih jedinstvenim. Očekujte da vas zabave svojim nestašlucima.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Egzotične mačke Devon Rex - igračke uživo',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Max','381621122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Nevjerojatno mekani Siberian mačići. Njihova mekoća i karakter osiguravaju vam puno maženja. Postanite deo njihove snežne priče.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Nevjerojatno mekani Siberian mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Šuša','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačići Cornish Rex - nježna elegancija. Njihova kovrdžava krzna i nežnost čine ih posebnim. Očekujte da budete očarani njihovom gracioznošću.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Mačići Cornish Rex - nježna elegancija',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Mia','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Savršeni partneri: Korat mačići dostupni. Njihova srebrna krzna i nežnost čine ih idealnim pratiocima. Postanite deo njihove elegantne priče.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Savršeni partneri: Korat mačići dostupni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Mister','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Luksuz u malom pakiranju: British Shorthair mačići. Njihova širina lica i odanost osiguravaju vam poseban odnos. Postanite vlasnik ovih malih aristokrata.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Luksuz u malom pakiranju: British Shorthair mačići',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Titi','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Ljubav i krzno: Himalayan mačići traže dom. Njihova dugačka krzna i nežnost čine ih neodoljivim. Očekujte da vam osvoje srce svojom elegancijom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Ljubav i krzno: Himalayan mačići traže dom',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Karamel','381621112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Mačići Tonkinese - odani i veseli. Njihova veselost i karakter osiguravaju vam puno smeha. Postanite vlasnik ove zabavne energije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Mačići Tonkinese - odani i veseli',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Lala','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Munchkin mačići - mala iznenađenja. Njihove kratke noge i ljubav prema igri čine ih jedinstvenim. Očekujte da vas očaraju svojom simpatičnošću.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','americanWirehair','Munchkin mačići - mala iznenađenja',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Pika','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Norveške šumske mačke - čuvari prirode u vašem domu. Njihova divlja priroda i šarm čine ih nezaboravnim. Postanite vlasnik ovih malih čuvara prirode.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Norveške šumske mačke - čuvari prirode u vašem domu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Džeki','381621234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Čudesne mačke Scottish Fold - ljupkost u krznu. Njihove presavijene uši i nežnost čine ih posebnim. Očekujte da vam osvoje srce svojom jedinstvenošću.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Čudesne mačke Scottish Fold - ljupkost u krznu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Čuperak','381611122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Egzotični mačići Bombay traže srodnu dušu. Njihova crna krzna i karakter osiguravaju vam neodoljivu vezu. Postanite deo njihove misteriozne priče.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Egzotični mačići Bombay traže srodnu dušu',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Lea','381631234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Havana Brown mačići - energija i zabava. Njihova veselost i karakter osiguravaju vam puno smeha. Postanite vlasnik ove zabavne energije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Havana Brown mačići - energija i zabava',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Šaša','381641122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Očaravajući mačići Birman spremni za usvajanje. Njihova ljepota i nežnost osiguravaju vam nezaboravnu vezu. Postanite vlasnik ove ljupkosti.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Očaravajući mačići Birman spremni za usvajanje',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Mila','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Šareni svet Balinese mačaka. Njihova dugačka krzna i graciozna priroda čine ih posebnim. Očekujte da vas očaraju svojom elegancijom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Šareni svet Balinese mačaka',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Beli','381631122233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Razigrani mačići Abyssinian traže igrače. Njihova energija i ljubav prema igri osiguravaju vam neprestanu zabavu. Postanite deo njihovih avantura.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Razigrani mačići Abyssinian traže igrače',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Tom','381641234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Persijski mačići - elegantni i nežni. Njihova lepota i karakter osiguravaju vam nezaboravnu vezu. Postanite vlasnik ove čarobne elegancije.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Persijski mačići - elegantni i nežni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Burek','381611234567',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Meke čarolije - Ragdoll mačići dostupni. Njihova mekoća i nežnost osiguravaju vam puno maženja. Očekujte da vas osvoje svojom nežnošću.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Meke čarolije - Ragdoll mačići dostupni',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Luna','381621112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Sphynx mačići - posebni i bez krzna. Njihova gola koža i karakter osiguravaju vam poseban odnos. Postanite vlasnik ovih unikatnih ljubimaca.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Sphynx mačići - posebni i bez krzna',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Pus','381631112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Sretne mačke Siamese traže ljubav. Njihova elegancija i odanost osiguravaju vam posebnu vezu. Postanite deo njihove priče o ljubavi.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Sretne mačke Siamese traže ljubav',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));
INSERT INTO ads (ad_status, ad_type, category, contact_name, contact_phone, created_on, description, free_of_charge, price, price_currency, price_is_fixed, ad_sell_type, subcategory, title, city_id, promotion_id, user_id) VALUES('ACTIVE', 'pets','cats','Mistik','381641112233',(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),'Ekskluzivni British Shorthair mačići za posebne ljude. Njihova širina lica i karakter čine ih jedinstvenim. Očekujte da vas očaraju svojom aristokratskom elegancijom.',0,(FLOOR(100 + RAND() * (10000 - 100 + 1))),'RSD',0,'SELL','aphroditeGiant','Ekskluzivni British Shorthair mačići za posebne ljude',(FLOOR(1 + (RAND() * 1000)))
,(FLOOR(1 + RAND() * (3 - 1 + 1))),(FLOOR(1 + RAND() * (3 - 1 + 1))));